-- Create the demos table
create table public.demos (
  id bigint generated by default as identity primary key,
  title text not null,
  image text not null,
  link_light text,
  link_dark text,
  link_rtl text,
  is_new boolean default false,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.demos enable row level security;

-- Create policies (modify as needed for your security model)
-- Allow read access to everyone
create policy "Enable read access for all users" on public.demos
  for select using (true);

-- Allow insert/update/delete for anonymous users (FOR DEMO PURPOSE ONLY - USE AUTH IN PROD)
-- Or ideally, only allow service_role to write, which the API uses.
-- However, if using the anon key in client-side API calls, you might need this.
-- But we are using server-side API routes.
-- If the API uses SERVICE_ROLE_KEY inside `route.ts`, it bypasses RLS.
-- If `route.ts` uses ANON_KEY, then we need a policy allowing write.
-- Currently fetching environment variables in `lib/supabase.ts` uses ANON_KEY by default.
-- So we need to allow public write for now, or assume the user will set up Auth.

-- UNSECURE POLICY FOR DEMO:
create policy "Enable write access for all users" on public.demos
  for insert with check (true);

create policy "Enable update access for all users" on public.demos
  for update using (true);

create policy "Enable delete access for all users" on public.demos
  for delete using (true);
