
create table public.site_settings (
    id bigint generated by default as identity primary key,
    profile_name text default 'Esaint',
    profile_role text default 'Fullstack Developer / Graphic Designer',
    profile_bio text default 'I''m a fullstack developer. Currently working with @knuthub as a developer and graphic designer.',
    email text default 'esaintdev@gmail.com',
    phone text default '+234 812 185 5275',
    whatsapp text default '+2348121855275',
    social_github text default 'https://github.com/esaintdev',
    social_linkedin text,
    social_dribbble text,
    social_behance text,
    social_facebook text default 'https://www.facebook.com/designwithesaint',
    social_instagram text default 'https://www.instagram.com/designwithesaint',
    cv_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);


alter table public.site_settings enable row level security;

create policy "Enable read access for all users" on public.site_settings
    for select using (true);

create policy "Enable write access for all users" on public.site_settings
    for insert with check (true);

create policy "Enable update access for all users" on public.site_settings
    for update using (true);

insert into public.site_settings (id) values (1) on conflict do nothing;
